// <auto-generated />
using System;
using Lost_Found.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lost_Found.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260830190931_AddIsDeletedToOglas")]
    partial class AddIsDeletedToOglas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lost_Found.Models.Claim", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("korisnikID");

                    b.Property<int>("ListingId")
                        .HasColumnType("integer")
                        .HasColumnName("oglasID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datumKreiranja")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datumRazresavanja");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("UserId", "ListingId");

                    b.HasIndex("ListingId");

                    b.ToTable("Potrazivanje", null, t =>
                        {
                            t.HasCheckConstraint("CK_Potrazivanje_Status", "\"status\" IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("Lost_Found.Models.Conversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("razgovorID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConversationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datumKreiranja")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ListingId")
                        .HasColumnType("integer")
                        .HasColumnName("oglasID");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("statusRazgovora");

                    b.HasKey("ConversationId");

                    b.HasIndex("ListingId")
                        .IsUnique();

                    b.ToTable("Razgovor", null, t =>
                        {
                            t.HasCheckConstraint("CK_Razgovor_Status", "\"statusRazgovora\" IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Lost_Found.Models.Listing", b =>
                {
                    b.Property<int>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("oglasID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ListingId"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer")
                        .HasColumnName("adminID");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kategorija");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("grad");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datumKreiranja")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer")
                        .HasColumnName("kreatorID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("opis");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("obrisan");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationDescription")
                        .HasColumnType("text")
                        .HasColumnName("OpisLokacije");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Photo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fotografija");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("naziv");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("tip");

                    b.HasKey("ListingId");

                    b.HasIndex("AdminId");

                    b.HasIndex("Category");

                    b.HasIndex("City");

                    b.HasIndex("CreatorId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Type");

                    b.ToTable("Oglas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Oglas_Latitude", "\"latitude\" IS NULL OR (\"latitude\" >= -90 AND \"latitude\" <= 90)");

                            t.HasCheckConstraint("CK_Oglas_Longitude", "\"longitude\" IS NULL OR (\"longitude\" >= -180 AND \"longitude\" <= 180)");

                            t.HasCheckConstraint("CK_Oglas_Tip", "\"tip\" IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Lost_Found.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("porukaID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("sadrzaj");

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("razgovorID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datumKreiranja")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("korisnikID");

                    b.HasKey("MessageId");

                    b.HasIndex("UserId");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("Poruka", (string)null);
                });

            modelBuilder.Entity("Lost_Found.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("korisnikID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vremeKreiranja")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lozinka");

                    b.Property<int>("TipKorisnika")
                        .HasColumnType("integer")
                        .HasColumnName("tipKorisnika");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("korisnickoIme");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Korisnik", null, t =>
                        {
                            t.HasCheckConstraint("CK_Korisnik_TipKorisnika", "\"tipKorisnika\" IN (0, 1)");
                        });

                    b.HasDiscriminator<int>("TipKorisnika");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Lost_Found.Models.Admin", b =>
                {
                    b.HasBaseType("Lost_Found.Models.User");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Korisnik_TipKorisnika", "\"tipKorisnika\" IN (0, 1)");
                        });

                    b.HasDiscriminator().HasValue(1);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@lostfound.local",
                            PasswordHash = "$2a$11$dp3ZWPpuZlt46loF6AoALutXdQDkMvmCRkRm6Kk5UZKbIRbtFEd8a",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Lost_Found.Models.StandardUser", b =>
                {
                    b.HasBaseType("Lost_Found.Models.User");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Korisnik_TipKorisnika", "\"tipKorisnika\" IN (0, 1)");
                        });

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Lost_Found.Models.Claim", b =>
                {
                    b.HasOne("Lost_Found.Models.Listing", "Listing")
                        .WithMany("Claims")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lost_Found.Models.StandardUser", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lost_Found.Models.Conversation", b =>
                {
                    b.HasOne("Lost_Found.Models.Listing", "Listing")
                        .WithOne("Conversation")
                        .HasForeignKey("Lost_Found.Models.Conversation", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Lost_Found.Models.Listing", b =>
                {
                    b.HasOne("Lost_Found.Models.Admin", "Admin")
                        .WithMany("SupervisedListings")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lost_Found.Models.StandardUser", "Creator")
                        .WithMany("Listings")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Lost_Found.Models.Message", b =>
                {
                    b.HasOne("Lost_Found.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lost_Found.Models.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lost_Found.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Lost_Found.Models.Listing", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Lost_Found.Models.User", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Lost_Found.Models.Admin", b =>
                {
                    b.Navigation("SupervisedListings");
                });

            modelBuilder.Entity("Lost_Found.Models.StandardUser", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
